### ISSUE TITLE
API to add new data

### ISSUE THREAD

**Issue by opn** [xdxdVSxdxd/HumanEcosystems#1]
How can I add an alternative data source. I'm looking to add content from the  [Discourse][https://meta.discourse.org/t/discourse-api-documentation/22706] froum?

**Comment by xdxdVSxdxd** [comment]
sorry for answering so late, but I just noticed these comments. The issues have been solved in the new, radically changed version of Human Ecosystems, which can be found here:

https://github.com/xdxdVSxdxd/HumanEcosystemsv3

I would suggest you switch to this other one because it is easier to use, and also fixes recent changes in API  usages on most social network providers. On top of that, we are not maintaining this one anymore.

Thanks!
