### ISSUE TITLE
Better Tutorials

### ISSUE THREAD

**Issue by opn** [xdxdVSxdxd/HumanEcosystems#2]
Ok - we need some better tutorials :) I've spend three or four attempts now getting this running without joy, and it's pretty clear I'm doing something basic wrong. I've got a development set-up on my laptop, and one on a server.

Can I suggest I help document a tutorial, and create a video regarding installation? What we can do is get a group of people together and do this online in a Hangout, where we can screenshare. 

One thing right now I'd like is a few test to check what could be going wrong. It looks like the database is created correctly, but the http requests are not getting any data. But I'm not too sure...

**Comment by hydrosquall** [comment]
Hi,

Not sure if you're still working on this, but for me while most of the visualizations don't work, this one `http://localhost/visualizations/updating-map/` does work for me with New Haven. I have been getting data from twitter and instagram, but not facebook.

The Chrome Inspector won't reveal the responses from Twitter, Facebook, etc because updater is just _invoking_ other PHP scripts, it doesn't make the calls directly. The data goes to the database, not to the blank `updater.php` file, hence inspecting the HTTP traffic won't reveal the payloads from the social media sites.

What you can do is go and look inside your database and see if it's getting populated. Make sure that the perimeter you've selected is an area where people are actively tweeting - perhaps try with a latitude/longitude around a very busy area, like New York City

A longer term thing would be to put this into a Docker container so someone can get up and running in a just a click :)

**Comment by xdxdVSxdxd** [comment]
sorry for answering so late, but I just noticed these comments. The issues have been solved in the new, radically changed version of Human Ecosystems, which can be found here:

https://github.com/xdxdVSxdxd/HumanEcosystemsv3

I would suggest you switch to this other one because it is easier to use, and also fixes recent changes in API  usages on most social network providers. On top of that, we are not maintaining this one anymore.

Thanks!
