### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by luizframalho** [xdxdVSxdxd/HumanEcosystems#3]
I'm trying to get this project working, but didn't have any luck.

This commit https://github.com/xdxdVSxdxd/HumanEcosystems/commit/6548f6bf92b7183bbda9dbd98d881c96d9e1c4cf#diff-3e3078d35a6ee6110f9ac20a52172f03R5 introduced a new column at the query `c.isgeodependent as isgeo`, but aparently the installer didn't create this column on my database.

I imagine this is just one of many other cases.

I've tried to reset my branch to the commit fb00558d5a2a3181c34825c662bbdc1377c38d10 and the problem was solved, but I still can't get any data.

Could you please point me to a stable commit where everything is working?
Also, I'd suggest not commint directly on the master branch, and create release tags of stable versions of the project.

Thanks for your help

**Comment by xdxdVSxdxd** [comment]
sorry for answering so late, but I just noticed these comments. The issues have been solved in the new, radically changed version of Human Ecosystems, which can be found here:

https://github.com/xdxdVSxdxd/HumanEcosystemsv3

I would suggest you switch to this other one because it is easier to use, and also fixes recent changes in API  usages on most social network providers. On top of that, we are not maintaining this one anymore.

Thanks!
