### ISSUE TITLE
Usage of Instagram API in Config File

### ISSUE THREAD

**Issue by hydrosquall** [xdxdVSxdxd/HumanEcosystems#4]
Hi,

Currently, the [config](https://github.com/xdxdVSxdxd/HumanEcosystems/blob/master/HE_v2/config_template.txt#L16) file only accepts a parameter for `in-client-id`, but the [install instructions](https://github.com/xdxdVSxdxd/HumanEcosystems/blob/master/HE_v2/installation-instructions.txt#L33) specify the need for the Client Secret token as well. 

Does the instagram client work without the Client secret token, or is the Instagram function currently broken?

**Comment by xdxdVSxdxd** [comment]
sorry for answering so late, but I just noticed these comments. The issues have been solved in the new, radically changed version of Human Ecosystems, which can be found here:

https://github.com/xdxdVSxdxd/HumanEcosystemsv3

I would suggest you switch to this other one because it is easier to use, and also fixes recent changes in API  usages on most social network providers. On top of that, we are not maintaining this one anymore.

Thanks!
