### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by cengizonkal** [xdxdVSxdxd/HumanEcosystems#5]
When using configuration page to put coordinates (installation/configuration.php) it always put 999 to database.

**Comment by bparlan** [comment]
I can confirm this problem and wish to include more details to it:
"min-max lat-lon" keys and values looks like have relation with problem. when I use those values, system starts to write lat and lot as "999" as can be seen in attached image. Wish to clearify that system do not directly fixes when I remove those min-max lat-lon info, even though 2 days past still I recieve 999 latlon in my 5-10% of content.
![humaneco01](https://cloud.githubusercontent.com/assets/3730152/19232926/39030b42-8eeb-11e6-8467-ebca03a78e71.jpg)

As a result, white circles in map expected to recieve content due to population distribution of island, but they recieve no content:
![humaneco02](https://cloud.githubusercontent.com/assets/3730152/19233065/de452e3c-8eeb-11e6-96f0-b276774eeea0.jpg)

Interestingly, we recieve more content from North America, UK, Turkey (which are normal due to content, but not ok within geographical aspect.
![humaneco03](https://cloud.githubusercontent.com/assets/3730152/19233072/e36c36bc-8eeb-11e6-8e03-d24e695e4664.jpg)

**Comment by xdxdVSxdxd** [comment]
sorry for answering so late, but I just noticed these comments. The issues have been solved in the new, radically changed version of Human Ecosystems, which can be found here:

https://github.com/xdxdVSxdxd/HumanEcosystemsv3

I would suggest you switch to this other one because it is easier to use, and also fixes recent changes in API  usages on most social network providers. On top of that, we are not maintaining this one anymore.

Thanks!
